In [1]:
import os
import pandas as pd

In [2]:
df = pd.read_json("raw_dataset.json")

In [24]:
df[df['path'] == 'f2py_skel/codegen/cfuncs.py']

,repo,pr_number,pr_title,pr_body,repo_star_count,commit_sha,path,patched_content,outgoing_dependencies,incoming_dependencies,metadata_files,comments
13,HaoZeke/f2py_skel,18,Intrinsic module derived types (Sourcery refac...,Pull Request #17 refactored by [Sourcery](http...,0,176b79219adda814a2fd84341f97dfc5dece5fb6,f2py_skel/codegen/cfuncs.py,"#!/usr/bin/env python3\n""""""\n\nC declarations,...","{'f2py_skel/__init__.py': '""""""Skeleton Fortran...",{'f2py_skel/codegen/rules.py': '#!/usr/bin/env...,"{'pyproject.toml': '[tool.poetry] name = ""f2py...",[]
19,HaoZeke/f2py_skel,18,Intrinsic module derived types (Sourcery refac...,Pull Request #17 refactored by [Sourcery](http...,0,085dfbd1527f90f4795225d1840d0e4dbd1813bf,f2py_skel/codegen/cfuncs.py,"#!/usr/bin/env python3\n""""""\n\nC declarations,...","{'f2py_skel/__init__.py': '""""""Skeleton Fortran...",{'f2py_skel/codegen/rules.py': '#!/usr/bin/env...,"{'pyproject.toml': '[tool.poetry] name = ""f2py...",[]

In [23]:
df[df['path'] == 'f2py_skel/codegen/cfuncs.py'].iloc[0] == df[df['path'] == 'f2py_skel/codegen/cfuncs.py'].iloc[1]

repo                      True
pr_number                 True
pr_title                  True
pr_body                   True
repo_star_count           True
commit_sha               False
path                      True
patched_content           True
outgoing_dependencies    False
incoming_dependencies     True
metadata_files            True
comments                  True
dtype: bool

In [18]:
df.groupby('path').agg(list)

,repo,pr_number,pr_title,pr_body,repo_star_count,commit_sha,patched_content,outgoing_dependencies,incoming_dependencies,metadata_files,comments
path,,,,,,,,,,,
STTBot/events/app_mention.py,[krdme/STTBot],[6],[STT Draft],[Not sure what i am doing],[0],[7b8d0235132da8fdaf3c47ffccad6e54c8a2896d],[# External\nimport json\nimport traceback\n\n...,[{}],[{}],[{'README.md': '# STTBot A simple Slack bot u...,[[{'body': 'This needs to match the function n...
ch04-language-foundations/asgi/asgi_summary.py,[jsonlehman/modern-apis-with-fastapi],[1],[Sourcery refactored main branch],[Branch `main` refactored by [Sourcery](https:...,[0],[908f0edaf8e5af59ff6a6e984b6d29841ec991e0],"[# Nothing to actually run, just explore these...",[{}],[{}],[{'README.md': '# Modern APIs with FastAPI cou...,[[{'body': 'Function `request` refactored with...
ch04-language-foundations/async/async_scrape/program.py,[jsonlehman/modern-apis-with-fastapi],[1],[Sourcery refactored main branch],[Branch `main` refactored by [Sourcery](https:...,[0],[908f0edaf8e5af59ff6a6e984b6d29841ec991e0],[import asyncio\nimport datetime\n\nimport htt...,[{}],[{}],[{'README.md': '# Modern APIs with FastAPI cou...,[[{'body': 'Function `get_title_range` refacto...
ch04-language-foundations/types/no_types_program.py,[jsonlehman/modern-apis-with-fastapi],[1],[Sourcery refactored main branch],[Branch `main` refactored by [Sourcery](https:...,[0],[908f0edaf8e5af59ff6a6e984b6d29841ec991e0],[from collections import namedtuple\n\nItem = ...,[{}],[{}],[{'README.md': '# Modern APIs with FastAPI cou...,[[{'body': 'Function `counter` refactored with...
ch04-language-foundations/types/types_program.py,[jsonlehman/modern-apis-with-fastapi],[1],[Sourcery refactored main branch],[Branch `main` refactored by [Sourcery](https:...,[0],[908f0edaf8e5af59ff6a6e984b6d29841ec991e0],[from collections import namedtuple\nfrom typi...,[{}],[{}],[{'README.md': '# Modern APIs with FastAPI cou...,[[{'body': 'Function `counter` refactored with...
ch05-a-realistic-api/services/openweather_service.py,[jsonlehman/modern-apis-with-fastapi],[1],[Sourcery refactored main branch],[Branch `main` refactored by [Sourcery](https:...,[0],[908f0edaf8e5af59ff6a6e984b6d29841ec991e0],[from typing import Optional\nimport httpx\n\n...,[{}],[{}],[{'README.md': '# Modern APIs with FastAPI cou...,[[{'body': 'Function `get_report_async` refact...
ch06-error-handling-and-perf/services/openweather_service.py,[jsonlehman/modern-apis-with-fastapi],[1],[Sourcery refactored main branch],[Branch `main` refactored by [Sourcery](https:...,[0],[908f0edaf8e5af59ff6a6e984b6d29841ec991e0],"[from typing import Optional, Tuple\nimport ht...",[{}],[{}],[{'README.md': '# Modern APIs with FastAPI cou...,[[{'body': 'Function `validate_units` refactor...
ch07-inbound-data/services/openweather_service.py,[jsonlehman/modern-apis-with-fastapi],[1],[Sourcery refactored main branch],[Branch `main` refactored by [Sourcery](https:...,[0],[908f0edaf8e5af59ff6a6e984b6d29841ec991e0],"[from typing import Optional, Tuple\nimport ht...",[{}],[{}],[{'README.md': '# Modern APIs with FastAPI cou...,[[{'body': 'Function `get_report_async` refact...
ch08-deployment/services/openweather_service.py,[jsonlehman/modern-apis-with-fastapi],[1],[Sourcery refactored main branch],[Branch `main` refactored by [Sourcery](https:...,[0],[908f0edaf8e5af59ff6a6e984b6d29841ec991e0],"[from typing import Optional, Tuple\nimport ht...",[{}],[{}],[{'README.md': '# Modern APIs with FastAPI cou...,[[{'body': 'Function `get_report_async` refact...
conan/tools/meson/meson.py,[conan-io/conan],[8965],[Fix/8964],[Changelog: Bugfix: Use meson toolchain file f...,[9294],[f1530d5e0245c0629f58d8814b8e3b178eeb473a],[-import os\n+from os.path import join\n\nfrom...,[{'conan/tools/build/__init__.py': 'from conan...,[{'conan/tools/meson/__init__.py': 'from conan...,"[{'conans/requirements.txt': 'PyJWT>=1.4.0, <2...",[[{'body': 'This seems to be added un-conditio...
conans/test/functional/toolchains/meson/_base.py,[conan-io/conan],[8965],[Fix/8964],[Changelog: Bugfix: Use meson toolchain file f...,[9294],[f1530d5e0245c0629f58d8814b8e3b178eeb473a],[import platform\nimport sys\nimport unittest\...,[{'conans/test/utils/tools.py': 'import json i...,[{'conans/test/functional/toolchains/meson/tes...,"[{'conans/requirements.txt': 'PyJWT>=1.4.0, <2...",[[{'body': 'We are not using CONAN_COMPILER_VE...
conans/test/functional/toolchains/meson/test_meson.py,[conan-io/conan],[8965],[Fix/8964],[Changelog: Bugfix: Use meson toolchain file f...,[9294],[f1530d5e0245c0629f58d8814b8e3b178eeb473a],[import os\nimport textwrap\n\nfrom conans.tes...,[{'conans/test/assets/sources.py': 'from jinja...,[{}],"[{'conans/requirements.txt': 'PyJWT>=1.4.0, <2...",[[]]
f2py_skel/codegen/cfuncs.py,"[HaoZeke/f2py_skel, HaoZeke/f2py_skel]","[18, 18]",[Intrinsic module derived types (Sourcery refa...,[Pull Request #17 refactored by [Sourcery](htt...,"[0, 0]","[176b79219adda814a2fd84341f97dfc5dece5fb6, 085...","[#!/usr/bin/env python3\n""""""\n\nC declarations...","[{'f2py_skel/__init__.py': '""""""Skeleton Fortra...",[{'f2py_skel/codegen/rules.py': '#!/usr/bin/en...,"[{'pyproject.toml': '[tool.poetry] name = ""f2p...","[[], []]"
f2py_skel/codegen/rules.py,"[HaoZeke/f2py_skel, HaoZeke/f2py_skel]","[18, 18]",[Intrinsic module derived types (Sourcery refa...,[Pull Request #17 refactored by [Sourcery](htt...,"[0, 0]","[176b79219adda814a2fd84341f97dfc5dece5fb6, 085...","[#!/usr/bin/env python3\n""""""\n\nRules for buil...","[{'f2py_skel/__init__.py': '""""""Skeleton Fortra...",[{'f2py_skel/frontend/f2py2e.py': '#!/usr/bin/...,"[{'pyproject.toml': '[tool.poetry] name = ""f2p...","[[], []]"
f2py_skel/frontend/crackfortran.py,"[HaoZeke/f2py_skel, HaoZeke/f2py_skel]","[18, 18]",[Intrinsic module derived types (Sourcery refa...,[Pull Request #17 refactored by [Sourcery](htt...,"[0, 0]","[176b79219adda814a2fd84341f97dfc5dece5fb6, 085...","[#!/usr/bin/env python3\n""""""\ncrackfortran ---...","[{'f2py_skel/__init__.py': '""""""Skeleton Fortra...","[{}, {}]","[{'pyproject.toml': '[tool.poetry] name = ""f2p...","[[], []]"
f2py_skel/stds/auxfuncs.py,"[HaoZeke/f2py_skel, HaoZeke/f2py_skel]","[18, 18]",[Intrinsic module derived types (Sourcery refa...,[Pull Request #17 refactored by [Sourcery](htt...,"[0, 0]","[176b79219adda814a2fd84341f97dfc5dece5fb6, 085...","[#!/usr/bin/env python3\n""""""\n\nAuxiliary func...","[{'f2py_skel/__init__.py': '""""""Skeleton Fortra...",[{'f2py_skel/codegen/func2subr.py': '#!/usr/bi...,"[{'pyproject.toml': '[tool.poetry] name = ""f2p...","[[], []]"
f2py_skel/stds/f90/simple_derived_types.py,"[HaoZeke/f2py_skel, HaoZeke/f2py_skel]","[18, 18]",[Intrinsic module derived types (Sourcery refa...,[Pull Request #17 refactored by [Sourcery](htt...,"[0, 0]","[176b79219adda814a2fd84341f97dfc5dece5fb6, 085...","[, ]","[{}, {}]","[{}, {}]","[{'pyproject.toml': '[tool.poetry] name = ""f2p...","[[], []]"
f2py_skel/stds/pyf/capi_maps.py,"[HaoZeke/f2py_skel, HaoZeke/f2py_skel]","[18, 18]",[Intrinsic module derived types (Sourcery refa...,[Pull Request #17 refactored by [Sourcery](htt...,"[0, 0]","[176b79219adda814a2fd84341f97dfc5dece5fb6, 085...","[#!/usr/bin/env python3\n""""""\n\nCopyright 1999...","[{'f2py_skel/__init__.py': '""""""Skeleton Fortra...",[{'f2py_skel/codegen/rules.py': '#!/usr/bin/en...,"[{'pyproject.toml': '[tool.poetry] name = ""f2p...","[[], []]"
python/rikai/parquet/dataset.py,[eto-ai/rikai],[445],[Tensorflow dataset],[],[141],[7f4a8778851b8de8f7c4eb7b3614875d4f3461b1],[# Copyright 2020 Rikai Authors\n#\n# Licens...,[{}],[{}],[{'README.md': '![Apache License](https://img....,[[]]
python/rikai/tf/__init__.py,[eto-ai/rikai],[445],[Tensorflow dataset],[],[141],[7f4a8778851b8de8f7c4eb7b3614875d4f3461b1],[+# Copyright 2022 Rikai Authors\n+#\n+# Lic...,[{}],[{}],[{'README.md': '![Apache License](https://img....,[[]]
python/rikai/tf/data.py,[eto-ai/rikai],[445],[Tensorflow dataset],[],[141],[7f4a8778851b8de8f7c4eb7b3614875d4f3461b1],[+# Copyright 2022 Rikai Authors\n+#\n+# Lic...,[{}],[{}],[{'README.md': '![Apache License](https://img....,[[{'body': 'Is the plan that we will try to in...
python/rikai/torch/transforms.py,[eto-ai/rikai],[445],[Tensorflow dataset],[],[141],[7f4a8778851b8de8f7c4eb7b3614875d4f3461b1],[# Copyright 2021 Rikai Authors\n#\n# Licens...,[{}],[{}],[{'README.md': '![Apache License](https://img....,[[]]
python/setup.py,[eto-ai/rikai],[445],[Tensorflow dataset],[],[141],[7f4a8778851b8de8f7c4eb7b3614875d4f3461b1],[import pathlib\n\nfrom setuptools import find...,[{}],[{}],[{'README.md': '![Apache License](https://img....,[[{'body': 'Should we discourage users from in...
python/tests/tf/test_tf_data.py,[eto-ai/rikai],[445],[Tensorflow dataset],[],[141],[7f4a8778851b8de8f7c4eb7b3614875d4f3461b1],[+# Copyright 2022 Rikai Authors\n+#\n+# Lic...,[{}],[{}],[{'README.md': '![Apache License](https://img....,[[{'body': 'Ok I see what you mean about the i...
recipes/libjpeg-turbo/all/conanfile.py,[conan-io/conan-center-index],[8592],[Fix libjpeg-turbo build for Android],[It didn't work for Android/armv7 because the ...,[1154],[b13e1773b6097ae5885d541624a8b7e50dd19cb9],"[from conans import ConanFile, CMake, tools\nf...",[{}],[{}],"[{'README.md': '<p align=""center""> <img sr...",[[{'body': 'This is not an actual fix. The re...